sudo: required
language: node_js
node_js:
  - '10'
services:
  - docker
before_install:
  - npm install -g yarn
cache: yarn
install: yarn install
script:
  - yarn build
  - docker build -t iannar .
notifications:
  email: false
